language: c

matrix:
    include:
        - os: osx
          env: PLATFORM=osx
          compiler: clang
        - os: linux
          env: PLATFORM=linux CXX=g++-4.9 CC=gcc-4.9
          compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux", "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5.3; fi
  - if [ "$TRAVIS_OS_NAME" == "linux", "$CXX" = "g++" ]; then export CXX="g++-5.3" CC="gcc-5.3"; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make