language: c

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - clang-3.7
            - g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: osx
      compiler: clang

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang-3.7; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.7; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      - CMAKE_VERSION="3.0.2"
      - wget "http://www.cmake.org/files/v3.0/cmake-${CMAKE_VERSION}.tar.gz"
      - openssl sha1 "cmake-${CMAKE_VERSION}.tar.gz"
      - tar xf "cmake-${CMAKE_VERSION}.tar.gz"
      - cd "cmake-${CMAKE_VERSION}"
      - ./bootstrap --prefix=~
      - make
      - make install
      - export PATH="~/bin:${PATH}"
      - cd ..
      - which cmake
      - cmake --version
    else
      brew update && brew unlink cmake
      brew install cmake
    fi

before_script:
   - mkdir build
   - cd build
   - ~/bin/cmake ..

script: make