language: c

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - kalakris-cmake
          packages:
            - clang-3.6
            - g++-5
            - cmake
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
          packages:
            - g++-5
            - cmake
    - os: osx
      compiler: clang

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang-3.6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.6; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update && brew unlink cmake
      brew install cmake
    fi

before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make