language: c

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - clang-3.7
            - g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: osx
      compiler: clang

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang-3.7; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.7; fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get remove cmake
      wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
      tar -xzf cmake-3.2.1.tar.gz
      cd cmake-3.2.1
      ./bootstrap
      make -j8
      sudo make install
      cd ..
      rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz
      which cmake
      cmake --version
    else
      brew update && brew unlink cmake
      brew install cmake
    fi

before_script:
   - mkdir build
   - cd build
   - cmake ..

script: make